version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: hypertube_db
    environment:
      POSTGRES_USER: hyperuser
      POSTGRES_PASSWORD: hyperpassword
      POSTGRES_DB: hypertube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
